CREATE TABLE DB_USERS (ID INT, NAME VARCHAR(50), PASSWORD VARCHAR(50), ROLE VARCHAR(50))

INSERT INTO DB_USERS("ID", "NAME", "PASSWORD", "ROLE") VALUES (1, 'admin', 'password', 'admin')
INSERT INTO DB_USERS("ID", "NAME", "PASSWORD", "ROLE") VALUES (2, 'bob', 'password', 'user')
